from enum import Enum


class ArasEvent(Enum):
    START_CONTROL_SERVICE_REQUESTED = "START_CONTROL_SERVICE_REQUESTED"
    STOP_CONTROL_SERVICE_REQUESTED = "STOP_CONTROL_SERVICE_REQUESTED"


class GoUpEvent(Enum):
    GO_UP_FAILED = "GO_UP_FAILED"
    GO_UP_SET_SETTINGS_FAILED = "GO_UP_SET_SETTINGS_FAILED"
    GO_UP_SET_SETTINGS_DONE = "GO_UP_SET_SETTINGS_DONE"
    GO_UP_DONE = "GO_UP_DONE"


class TakeOffEvent(Enum):
    TAKE_OFF_CONNECTION_FAILED = "TAKE_OFF_CONNECTION_FAILED"
    TAKE_OFF_CONNECTED_BUT_FAILED = "TAKE_OFF_CONNECTED_BUT_FAILED"
    TAKE_OFF_DONE = "TAKE_OFF_DONE"


class WakeUpEvent(Enum):
    WAKE_UP_DONE = "WAKE_UP_DONE"
